name: Build and Test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Xcode Cache
        id: xcode-cache
        uses: actions/cache@v2
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-cache

      - name: Cache pods
        uses: actions/cache@v2
        id: pods-cache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Dependencies
        if: steps.pods-cache.outputs.cache-hit != 'true'
        run: |
          pod install --repo-update

      - name: Test
        run: |
          fastlane tests
