name: Bump version
on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  release:
    name: Fastlane Beta Release To Testflight
    runs-on: macos-latest
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.FUNFUNFUN_BOT_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Build and Send to Testflight
        run: fastlane beta
